### PR TITLE
Feature/thunder strikes/s2 a 66 infinity scroll for movie page/jackson shen

### PR DESCRIPTION
**Pull request by Phantom-Shen**

### CODE REVIEW

**Comment by victorincode** [comment]
Looks good! do we have any use for movie-dashboard anymore or is this being replaced in its entirety by movie-browse?

**Review by EricKumar141 — APPROVED** [review]
looks good to me

**Comment by EricKumar141** [comment]
oh we have 1 minor conflict with json file, not sure what to do

**Comment by victorincode** [comment]
This is probably the most annoying conflict I've seen. 😂

**Comment by victorincode** [comment]
Too many thousands of lines of code. Better to close this and do a new pull request after doing a fresh pull.

**Pull request closed without merging**
