### PR TITLE
Hotfix/team_ac/project_scaffold

### PR DESCRIPTION
**Pull request by aabrahamx**
Changes I've Made
-----

- moved all project files and directories to parent main directory
- added `eslint` to the project
- refactored `style.css`
- created reusable mixin styles for the app

### CODE REVIEW

**Review by piaoxianer — COMMENTED** [review]
There are 3266 lines added in the package-lock.json file. Those dependencies should be used to configure the eslint, does all of them we need to use in our project?

**Review by piaoxianer — COMMENTED** [review]
The scss stuff looks good for me.

**Review by piaoxianer — COMMENTED** [review]
Looks more structured

**Comment by aabrahamx** [comment]
When I installed `eslint`

> There are 3266 lines added in the package-lock.json file in the commit 'eslint & .vscode setting add'. Those dependencies should be used to configure the eslint, does all of them we need to use in our project?

I believe those changes applied when I installed `eslint` from npm. I am not totally sure what all those lines do, but I believe it is something that came with the `eslint` install.

**Review by spartamonk — APPROVED** [review]
thanks for the implementing the new configurations as discussed

**Pull request merged**
