### PR TITLE
Feature/thunder strikes/s2 a 78 use resolver to hold http request/jackson shen

### PR DESCRIPTION
**Pull request by Phantom-Shen**

### CODE REVIEW

**Comment by EricKumar141** [comment]
looks good except for conflict with app-routing.module.ts. I think can resolve if we combine the three imports at the top of file and remove the 2nd loadchildren in path "movie-browse"

**Comment by victorincode** [comment]
Looks good. The conflict is minor.

Is there any reason we're going with pressing enter to start searching for movies instead of the previous implementation that did it as you typed? I think the user experience outweighs the performance hit.

**Review by victorincode — APPROVED** [review]

**Comment by Phantom-Shen** [comment]
Oh I saw it says it's approved, and I just merge it.

**Comment by victorincode** [comment]
> Oh I saw it says it's approved, and I just merge it.

I solved the conflict. Did what Eric said.

**Comment by Phantom-Shen** [comment]
> Looks good. The conflict is minor.
> 
> Is there any reason we're going with pressing enter to start searching for movies instead of the previous implementation that did it as you typed? I think the user experience outweighs the performance hit.

We can fetch search result by specifying Url with format "/search/:title/:page" now. But, each time when navigating to a new page, e.g. "search/thor/2", it will refresh the current page. So, probably, better to let the users to decide when they want to start searching

**Comment by Phantom-Shen** [comment]
> Looks good. The conflict is minor.
> 
> Is there any reason we're going with pressing enter to start searching for movies instead of the previous implementation that did it as you typed? I think the user experience outweighs the performance hit.

I will try and see if there's any way I can avoid the refreshing   :DD

**Comment by victorincode** [comment]
> > Looks good. The conflict is minor.
> > Is there any reason we're going with pressing enter to start searching for movies instead of the previous implementation that did it as you typed? I think the user experience outweighs the performance hit.
> 
> I will try and see if there's any way I can avoid the refreshing :DD

Actually, that seems complicated. Haha. I was just wondering why. It works fine this way too.

**Comment by Phantom-Shen** [comment]
> > Oh I saw it says it's approved, and I just merge it.
> 
> I solved the conflict. Did what Eric said.

Thx for helping solve the conflict!

**Comment by victorincode** [comment]
👍🏼

**Pull request merged**
